name: kushi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.3.1+1
  cloud_firestore: ^0.9.0+1
  firebase_messaging: ^4.0.0+1
  flutter_local_notifications: ^1.4.4+2
  location: ^3.0.2
  wakelock: ^0.1.4+1
  google_maps_flutter: ^0.4.0
  cupertino_icons: ^0.1.2
  generic_bloc_provider: ^1.0.8
  provider: ^2.0.1
  page_transition: ^1.1.4
  simple_animations: ^1.3.7
  shared_preferences: ^0.5.6+3
  flutter_staggered_grid_view: ^0.3.0
  flutter_launcher_icons: "^0.7.3"
  cached_network_image: ^2.2.0+1
  flutter_masked_text: ^0.8.0
  datetime_picker_formfield: ^1.0.0
  pin_code_fields: ^2.3.0+3
  date_format: ^1.0.8
  flutter_svg: ^0.18.0 
  sticky_headers: ^0.1.8
  json_annotation: ^2.4.0
  rflutter_alert: ^1.0.2
  carousel_slider: ^1.3.0
  image_picker: ^0.6.5+2
  http: ^0.12.0+4
  http_parser: ^3.1.4
  basic_utils: ^1.5.1
  get_it: ^1.0.3
  intl: ^0.16.1
  hexcolor: ^1.0.1
  audioplayers: ^0.15.1
  font_awesome_flutter: ^8.5.0
  flutter_slidable: ^0.4.9
  culqi_flutter: ^1.0.1
  url_launcher: ^5.5.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/img/kushi_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/kushilogo.png
    - assets/img/upLoadPhoto.png
    - assets/img/avatarPermanent.png
    - assets/img/shoping.png
    - assets/img/empyCardShoping.png
    - assets/img/logoplin.png
    - assets/img/logoyape.png
    - assets/img/progressImage.gif
    - assets/cardImage/mastercard.svg
    - assets/cardImage/visa.svg
    - assets/cardImage/americanexpress.svg
    - assets/cardImage/hsbc.svg
    - assets/cardImage/citi.svg
    - assets/cardImage/bankofamerica.svg
    - assets/cardImage/apple.svg
    - assets/cardImage/bcp-seeklogo.com.svg
    - assets/img/loaderStock.gif
    - assets/img/giflStock.gif
    - assets/img/noConnection.png
    - assets/img/gifconnection.gif
    - assets/img/gifcarrucel.gif
    - assets/img/paymentplin.jpg
    - assets/img/mylocations.png
    - assets/img/locationOn.png
    - assets/img/notfontAddress.png
    - assets/img/pendiente.png
    - assets/img/proceso.png
    - assets/img/finalizado.png
    - assets/img/loderOrder.gif
    - assets/img/notfoundQr.png
    - assets/img/notFountDataService.png
    - assets/img/nosearchbusiness.png
    - assets/img/gifproducts.gif
    - assets/images/
    - assets/alerts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kushi
      fonts:
        - asset: fonts/Kushi.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
